### ISSUE TITLE
d6d3be3 is breaking kal -s GSM900 channel visability

### ISSUE THREAD

**Issue by ValZapod** [librtlsdr/librtlsdr#81]
@hayguen So it is pretty bad, this is latest from debian testing

```
Found 1 device(s):
  0:  Astrometa DVB-T/DVB-T2

Using device 0: Astrometa DVB-T/DVB-T2
Found Rafael Micro R828D tuner
Exact sample rate is: 270833.002142 Hz
[R82XX] PLL not locked!
kal: Scanning for GSM-900 base stations.
GSM-900:
	chan: 21 (939.2MHz - 29.522kHz)	power: 309234.12
	chan: 26 (940.2MHz - 35.615kHz)	power: 377635.23
	chan: 45 (944.0MHz - 28.165kHz)	power: 362743.06
	chan: 67 (948.4MHz - 28.795kHz)	power: 1310182.29
	chan: 72 (949.4MHz - 34.350kHz)	power: 1489620.71
	chan: 93 (953.6MHz - 29.160kHz)	power: 332862.81
	chan: 97 (954.4MHz - 28.435kHz)	power: 696026.76
	chan: 99 (954.8MHz - 28.287kHz)	power: 454571.67
	chan: 102 (955.4MHz - 28.366kHz)	power: 1636962.97
	chan: 113 (957.6MHz - 28.956kHz)	power: 565481.46

```

this is on master of this repo (+1 channel, 67)

```
Found 1 device(s):
  0:  Astrometa DVB-T/DVB-T2

Using device 0: Astrometa DVB-T/DVB-T2
Found Rafael Micro R828D tuner
Exact sample rate is: 270833.002142 Hz
[R82XX] PLL not locked!
kal: Scanning for GSM-900 base stations.
GSM-900:
	chan: 21 (939.2MHz - 29.587kHz)	power: 256824.66
	chan: 26 (940.2MHz - 25.204kHz)	power: 281389.88
	chan: 45 (944.0MHz - 28.165kHz)	power: 357661.50
        chan: 72 (949.4MHz - 24.853kHz)	power: 1573023.70
	chan: 93 (953.6MHz - 29.229kHz)	power: 297849.48
	chan: 97 (954.4MHz - 28.500kHz)	power: 727250.45
	chan: 99 (954.8MHz - 28.360kHz)	power: 431893.70
	chan: 102 (955.4MHz - 28.442kHz)	power: 1310975.42
	chan: 113 (957.6MHz - 29.011kHz)	power: 405155.08

```

this is on commit applying mutability patch (we ALREADY LOST 21 channel, but genius mutability patch sets precisely 28.xxx, that is nice)! 

```
Found 1 device(s):
  0:  Astrometa DVB-T/DVB-T2
Using device 0: Astrometa DVB-T/DVB-T2
Found Rafael Micro R828D tuner
Exact sample rate is: 270833.002142 Hz
[R82XX] PLL not locked for 2125000 Hz!
kal: Scanning for GSM-900 base stations.
GSM-900:
	chan: 25 (940.0MHz - 34.724kHz)	power: 183211.42
	chan: 26 (940.2MHz - 24.860kHz)	power: 290727.87
	chan: 45 (944.0MHz - 28.835kHz)	power: 335290.33
	chan: 72 (949.4MHz - 34.234kHz)	power: 1427133.44
	chan: 93 (953.6MHz - 28.280kHz)	power: 291440.57
	chan: 97 (954.4MHz - 28.107kHz)	power: 580485.23
	chan: 99 (954.8MHz - 28.199kHz)	power: 439338.89
	chan: 102 (955.4MHz - 28.028kHz)	power: 1355931.35
	chan: 113 (957.6MHz - 28.083kHz)	power: 442382.52

```
This is on development (obviously it is reproducible):
```
Found 1 device(s):
  0:  Astrometa DVB-T/DVB-T2

Using device 0: Astrometa DVB-T/DVB-T2
Found Rafael Micro R828D tuner
Exact sample rate is: 270833.002142 Hz
kal: Scanning for GSM-900 base stations.
GSM-900:
	chan: 25 (940.0MHz - 34.524kHz)	power: 101289.01
	chan: 26 (940.2MHz - 34.364kHz)	power: 511929.91
	chan: 72 (949.4MHz - 33.922kHz)	power: 462179.91
	chan: 73 (949.6MHz - 33.926kHz)	power: 196378.37 //this one it does not even find usually!

```

So it is bad.

Will try to bisect it tomorrow.

**Comment by ValZapod** [comment]
Nope, your latest commit does not fix the issue. Alsoplease look into new linking problem because of new gcc in Debian Testing. #82

**Comment by hayguen** [comment]
please put attached bash script [testkal.sh.txt](https://github.com/librtlsdr/librtlsdr/files/5116924/testkal.sh.txt)
(.sh isn't accepted by github) into the unmodified directory of kal from steve:
https://github.com/steve-m/kalibrate-rtl

in the script i put the directories for different libraries:
```
PA=( "" \
  "librtlsdr-master" \
  "librtlsdr-dev-pre-fix" \
  "librtlsdr-dev" \
  "librtlsdr-dev" \
  "librtlsdr-dev" \
 )
```
$HOME is prepended and "-build/src" is prepended for the LD_LIBRARY_PATH.
* librtlsdr-master is what it says, the master branch of https://github.com/librtlsdr/librtlsdr
* librtlsdr-dev-pre-fix is the development branch, detached on commit 2d56e3202c3d855a64fb7cd983606dae486d8c6e
* librtlsdr-dev is head of development branch

please adjust if required, run the script .. then save/send me all output files test_kal_lib*

i get following output (compressed the empty lines):
```
ayguen@ubuntu:~/kalibrate-rtl_steve/src$ ./testkal.sh 
LIBRTLSDR_OPT = ''
LIBRTLSDR_OPT = ''
git status
git log -n 1
***********************************************
test with library /home/ayguen/librtlsdr-master-build/src
*** LD_LIBRARY_PATH=/home/ayguen/librtlsdr-master-build/src ldd ./kal
	librtlsdr.so.0 => /home/ayguen/librtlsdr-master-build/src/librtlsdr.so.0 (0x00007fcd9431f000)

*** LD_LIBRARY_PATH=/home/ayguen/librtlsdr-master-build/src ./kal -s GSM900
*** # channels: 13

*** LD_LIBRARY_PATH=/home/ayguen/librtlsdr-master-build/src ./kal -s GSM900
*** # channels: 12

***********************************************
test with library /home/ayguen/librtlsdr-dev-pre-fix-build/src
*** LD_LIBRARY_PATH=/home/ayguen/librtlsdr-dev-pre-fix-build/src ldd ./kal
	librtlsdr.so.0 => /home/ayguen/librtlsdr-dev-pre-fix-build/src/librtlsdr.so.0 (0x00007fcf582f5000)

*** LD_LIBRARY_PATH=/home/ayguen/librtlsdr-dev-pre-fix-build/src ./kal -s GSM900
*** # channels: 15

*** LD_LIBRARY_PATH=/home/ayguen/librtlsdr-dev-pre-fix-build/src ./kal -s GSM900
*** # channels: 13

***********************************************
test with library /home/ayguen/librtlsdr-dev-build/src

*** LD_LIBRARY_PATH=/home/ayguen/librtlsdr-dev-build/src ldd ./kal
	librtlsdr.so.0 => /home/ayguen/librtlsdr-dev-build/src/librtlsdr.so.0 (0x00007f88c019b000)

*** LD_LIBRARY_PATH=/home/ayguen/librtlsdr-dev-build/src ./kal -s GSM900
*** # channels: 24

*** LD_LIBRARY_PATH=/home/ayguen/librtlsdr-dev-build/src ./kal -s GSM900
*** # channels: 26
```

you see, i can around 13 channels for the system's librtlsdr0 and quite similar value with the master branch. with head of development branch, i get much more channels: around 25.
you also see, that every run detects slightly different channels.


then, go to the sources of librtlsdr-dev and do edit
* tuner_r82xx.c: set `PRINT_VGA_REG` to 1  approx at line 35
* librtlsdr.c: set `LOG_API_CALLS` to 1 at line 98
build it, activate the `PEXEC="4"` in testkal.sh, run it again and save/send me the output files.

then, go to the sources of librtlsdr-dev and do edit
* librtlsdr.c: set `INIT_R820T_TUNER_GAIN` to 1 at line 101
build it, activate the `PEXEC="5"` in testkal.sh, run it again and save/send me the output files.

all the runs take a while.

**Comment by ValZapod** [comment]
> head of development branch, i get much more channels: around 25

So it is opposite for you? I think you said it is the same behaviour for you ((

> * LOG_API_CALLS

So you want all API calls? Like with gdb, hehe?

**Comment by hayguen** [comment]
> So it is opposite for you? I think you said it is the same behaviour for you ((

now, it's opposite for me .. meanwhile having changed initialization of R820T registers:
* now initializing automatic gain for LNA and Mixer  (i may need to check again)
* now initializing fixed VGA gain: register content 0xb (= decimal value 11), expecting RTL2832's control line off
* RTL2832's control line to tuner was and is deactivated

in the master branch it was quite different:
* RTL2832's control line was NEVER active - sort of broken
* VGA was set to 0xF5, expecting RTL2832's control line to be active!

> So you want all API calls? Like with gdb, hehe?

not exactly .. but sort of.
i wondered that kal is doing very very few API calls!

**Comment by ValZapod** [comment]
Olease fix https://github.com/librtlsdr/librtlsdr/blob/04cab17135d2a466954673752417fa65379c66ad/src/tuner_r82xx.c#L1910 meanwhile I will try to think of smth with those API calls.

**Comment by hayguen** [comment]
> if ( priv->valR30H > 6 )

fixed that
and deactivated all the stuff modifying R820T I2C registers via environment vars, which was only for tests

**Comment by ValZapod** [comment]
Nice!

**Comment by ValZapod** [comment]
Wait a secnd, this is still wrong. & 0x03 is max 3 and then you check for
more than 3??

**Comment by hayguen** [comment]
oh my! you are right. the check should have been before masking .. or better without masking

**Comment by ValZapod** [comment]
1) You know that is not the only problem that is there, on development the ppm error is more like 34 and on master it is 29. With the same everything else.

2) So is there anything in d6d3be3 and follow up fixit commit besides that priv->valR30H > 6 thing that can be breaking for chan: > 73??

**Comment by hayguen** [comment]
@ValZapod : 
sorry, but i'm unable to see the problem in d6d3be3
priv->valR30H stuff is only used, if an appropriate environment variable would have been set. i doubt, this is the case.

please, would also someone else check this problem?!
.. and produce logs with the script i sent with https://github.com/librtlsdr/librtlsdr/issues/81#issuecomment-679027156

**Comment by ValZapod** [comment]
> unable to see the problem in [d6d3be3](https://github.com/librtlsdr/librtlsdr/commit/d6d3be3952a43c61643c9973658dbc5a22fb2cb2)

Well, it is there. Wait, all this time you were trying smth else?? But as I said I bisected it to that commit... It is 100% there, and in fix it commit that is https://github.com/librtlsdr/librtlsdr/commit/622b61447962a9aa321abc4c58a978f213ff8362

**Comment by hayguen** [comment]
> Wait, all this time you were trying smth else??
No.

**Comment by ValZapod** [comment]
Okay, so I set up all that stuff. But I do not understand your idea of the script, it does not matter how many channels are there, the main problem is that developent does not see channels higher than 73.

Also, of course dev on commit 2d56e32 will not link as as I said you will need to apply my "extern" patch (but whatever). Indeed it shows less channels.

Also, should not you have applied API logger on master as well? What is the point to not have API logs from master?

**Comment by ValZapod** [comment]
And, no INIT_R820T_TUNER_GAIN 1 does not fix the issue.

Okay, I did like a test. That is all you have 
```
Found 1 device(s):
  0:  Astrometa DVB-T/DVB-T2

Using device 0: Astrometa DVB-T/DVB-T2
LOG: rtlsdr_open(0)
Found Rafael Micro R828D tuner
LOG: rtlsdr_get_xtal_freq(rtl_freq, tuner_freq)
LOG: rtlsdr_get_xtal_freq(rtl_freq, tuner_freq)
LOG: rtlsdr_set_sample_rate(samp_rate 270833)
Exact sample rate is: 270833.002142 Hz
LOG: rtlsdr_get_xtal_freq(rtl_freq, tuner_freq)
kal: Scanning for GSM-900 base stations.
GSM-900:
    chan:   25 (940.0MHz - 34.621kHz)    power:  140478.94
    chan:   26 (940.2MHz - 24.496kHz)    power:  338676.00
    chan:   49 (944.8MHz - 34.329kHz)    power:  126336.45
    chan:   72 (949.4MHz - 24.111kHz)    power:  810622.05
    chan:   73 (949.6MHz - 23.641kHz)    power:  262201.37

Difference of offsets between channels is >1kHz. This likely means that the correct PPM is too far away and you need to provide a rough estimate using the '-e' option. Try tuning against a local FM radio or other known frequency first.


*** # channels: 5
```

**Comment by hayguen** [comment]
oh my! we were all the time looking for the wrong thing!
following warning from your latest message explains it:

> Difference of offsets between channels is >1kHz. This likely means that the correct PPM is too far away and you need to provide a rough estimate using the '-e' option. Try tuning against a local FM radio or other known frequency first.

it could have been seen earlier - up from your first log, cause **ALL** channels have big frequency error .. and the offsets are several kHz away.

had you run older version of kal, not giving this warning?
however, this is history.

not sure, but IMHO, you can't rely on the results of kal without giving it a (good) starting point for the ppm with '-e' option. in general, GSM900 with GMSK modulation is sensitive to frequency error. what i'm unsure about: up to what frequency error can kal detect the channel?
in case, the ppm error and temperature is stable, the higher channels (with higher frequency) have a bigger absolute frequency error. this might explain, why kal doesn't receive/detect the higher channels.

however, with a dongle without TCXO (temperature stabilisation of the oscillator), you need to warm up the dongle, thus run one of the tools for some minutes .. up to 15 minutes or that. at some places i read 30 min .. not sure. then, run kal systematically, e.g. in steps of 10 ppm, i'd say in a range from -150 through 0 up to +150 ppm and save all results.

i'll need to do the same - this time with a cheaper dongle without TCXO.
the development branch includes at least https://github.com/steve-m/librtlsdr/pull/10 which should reduce the tuning error.

meanwhile i got 1st results for a cheap dongle without option '-e' - after some warming up:
* osmocom drivers: two times 3 channels, with offset around 39 kHz (both times)
* master of this fork: two times 4 channels, with offset around 39 kHz
* development - previous to fix: two times 0 channels !
* hottest head of development: 5 and 4 channels, BUT with quite different offsets ranging von -12 to +39 kHz!!!, with some points in between

i would test again .. with option '-e' trying different values, as written above ..

**Comment by ValZapod** [comment]
> without giving it a (good) starting point for the ppm with '-e' option

I usually use -e 29 option. It is no good as well, the offsets are still "difference of offsets between channels is >1kHz". And noo, the same warning with master branch.

**Comment by ValZapod** [comment]
At this point I think we should just try to bisect that two commits line by line.

**Comment by hayguen** [comment]
> At this point I think we should just try to bisect those two commits line by line.

Probably the only way.
Meanwhile I've one more guess, after I had a look into the specs of gsm900 ..

**Comment by hayguen** [comment]
> I usually use -e 29 option. It is no good as well, the offsets are still "difference of offsets between channels is >1kHz"


came home and all the ppm test were finished, here's the best result:

```
*** LD_LIBRARY_PATH=/home/ayguen/librtlsdr-dev-build/src LIBRTLSDR_OPT=  ./kal -s GSM900 -e 70
Fri 04 Sep 2020 11:25:35 AM CEST
Found 1 device(s):
  0:  Generic RTL2832U OEM

Using device 0: Generic RTL2832U OEM
Found Rafael Micro R820T/2 tuner
Exact sample rate is: 270833.002142 Hz
kal: Scanning for GSM-900 base stations.
process options '' from environment 'LIBRTLSDR_OPT'
GSM-900:
    chan:    2 (935.4MHz - 10.174kHz)    power:  '659'501.76
    chan:    3 (935.6MHz - 10.077kHz)    power:  '547'545.34
    chan:    4 (935.8MHz - 10.021kHz)    power:  '536'518.71
    chan:    5 (936.0MHz - 10.035kHz)    power:  '836'373.67
    chan:    6 (936.2MHz - 9.949kHz)     power:  '404'092.90
    chan:   42 (943.4MHz - 10.158kHz)    power:  '949'898.48
    chan:   43 (943.6MHz - 10.084kHz)    power: 2'060'903.62
    chan:   44 (943.8MHz - 10.090kHz)    power:  '711'786.31
    chan:   45 (944.0MHz - 10.021kHz)    power:  '329'193.11
    chan:   46 (944.2MHz - 10.017kHz)    power:  '414'033.76
    chan:   48 (944.6MHz - 9.933kHz)     power:  '482'707.67
    chan:   51 (945.2MHz - 10.251kHz)    power: 1'021'971.53
    chan:   52 (945.4MHz - 10.238kHz)    power:  '810'956.85
    chan:   53 (945.6MHz - 10.187kHz)    power:  '857'654.29
    chan:   57 (946.4MHz - 10.072kHz)    power: 2'253'480.10
    chan:   61 (947.2MHz - 9.901kHz)     power:  '454'798.03
    chan:   64 (947.8MHz - 10.285kHz)    power:  '609'548.26
    chan:   66 (948.2MHz - 10.218kHz)    power:  '829'214.23
    chan:   70 (949.0MHz - 10.098kHz)    power: 1'641'369.65
    chan:   77 (950.4MHz - 10.298kHz)    power:  '716'261.15
    chan:   82 (951.4MHz - 10.113kHz)    power:  '975'189.49
    chan:   83 (951.6MHz - 10.084kHz)    power:  '701'509.14
    chan:   85 (952.0MHz - 10.031kHz)    power: 2'411'069.76
    chan:  115 (958.0MHz - 10.356kHz)    power: 1'675'593.16

*** # channels: 24
```

strongest channel is 85. running kal with options `-e 70 -c 85` results in 80.x ppm.
looking in the scan log file for 80 ppm gave 21 and 19 channels.
the best results i saw for the osmocom/system driver without the warning was: 5 channels.
however compared to the results without `-e` it's very big difference.

to see, how offset goes towards 0, here the results for `-e 80`:
```
*** LD_LIBRARY_PATH=/home/ayguen/librtlsdr-dev-build/src LIBRTLSDR_OPT=  ./kal -s GSM900 -e 80
Fri 04 Sep 2020 11:31:52 AM CEST
...
GSM-900:
    chan:    2 (935.4MHz - 635Hz)    power:  518217.16
    chan:    4 (935.8MHz - 893Hz)    power:  519850.34
    chan:    5 (936.0MHz - 924Hz)    power:  911736.66
    chan:    6 (936.2MHz - 865Hz)    power:  349771.80
    chan:   42 (943.4MHz - 555Hz)    power:  832383.71
    chan:   43 (943.6MHz - 948Hz)    power: 2308222.02
    chan:   45 (944.0MHz - 894Hz)    power:  443297.32
    chan:   46 (944.2MHz - 791Hz)    power:  380596.59
    chan:   48 (944.6MHz - 814Hz)    power:  303806.00
    chan:   51 (945.2MHz - 682Hz)    power:  744730.75
    chan:   52 (945.4MHz - 671Hz)    power:  717577.09
    chan:   53 (945.6MHz - 605Hz)    power:  941565.91
    chan:   57 (946.4MHz - 915Hz)    power: 2145032.42
    chan:   61 (947.2MHz - 762Hz)    power:  401528.15
    chan:   64 (947.8MHz - 666Hz)    power:  655586.76
    chan:   66 (948.2MHz - 602Hz)    power:  777010.44
    chan:   67 (948.4MHz - 575Hz)    power: 1159755.64
    chan:   82 (951.4MHz - 508Hz)    power: 1058114.46
    chan:   85 (952.0MHz - 795Hz)    power: 2820026.07
    chan:  115 (958.0MHz - 743Hz)    power: 1480808.96
    chan:  120 (959.0MHz - 537Hz)    power:  390906.05

*** # channels: 21
```

you can see, that a negative offset means, that you should increase the ppm value for `-e`.
the increment is roundabout:  avg(offset) in Hz / frequency in MHz
in my case above: 70 ppm - ( -10000 / 950 ) = 70 + 10.5 ~= 80.5 ppm

@ValZapod : following this, you should increase your ppm value by roundabout 30 ppm

this isn't the final solution .. and i'll now continue to track the initial error / check what came in my mind .. but would be interesting to see, what results you get with better initial ppm value!

**Comment by hayguen** [comment]
> Meanwhile I've one more guess, after I had a look into the specs of gsm900 .. will test this evening

GSM900 is GMSK modulation with bitrate of ~ 270 kBit. For GMSK this is also the symbolrate and also roughly the bandwidth.
now, kal does sample at exactly the symbolrate - not using any oversampling.
usually (on demodulation) an oversampling of factor 2 or even more is used: samplerate >= symbolrate * 2.

initially looking at gain/agc .. i could not spot the error in the bisected commits d6d3be3952a43c61643c9973658dbc5a22fb2cb2 / 622b61447962a9aa321abc4c58a978f213ff8362  and could not think of a connection to the improved bandfilters.
knowing the new smallest bandwidth is about 200 kHz with asymmetrical filtering (define WITH_ASYM_FILTER = 1) and about 290 kHz deactivating asymmetric filtering. quite important: without explicit bandwidth setting, the filter is set automatically from the samplerate.
for short: 290 kHz filter doesn't leave much room for frequency error assuming a coarse bandwidth of 270 kHz!

testing on commit 622b61447962a9aa321abc4c58a978f213ff8362 : setting WITH_ASYM_FILTER  to 0 does help and removing the lower bandwidths in the `const struct IFinfo IFi[]` table does help either.
BUT, the initial ppm error (option '-e') must already be **near** the correct value. From my tests with the R820T(2?) dongle in plastic housing with a measured ppm value of ~81 ppm,  an error of 40 ppm is the limit, which corresponds to about ~ 38 kHz.

realizing all this, i switched to head of the development branch:
WITH_ASYM_FILTER is already 0. there's no need for the asymmetric filter stuff - having highpass, lowpass filters and fine tunable band center.
having the ppm value in a good range, much more channels are detected, cause of improved AGC and VGA settings.
with this increased signal level, even the narrow filter looks to be compensated!

however, additionally tried increasing the bandwidth with the enviroment variable `LIBRTLSDR_OPT`, which is processed from librtlsdr:
```
$ LIBRTLSDR_OPT="bw=600"  ./kal -e 120 -s GSM900
```
the results for the above 600 kHz bandwidth didn't really improve things. i even got slightly more outliers in the measured frequency offset, depending on the configured ppm/frequency error.

in the end: i'd suggest using kal as is, but running it multiple times. to cover /test a range of -150 .. +150 ppm run it up to 5 times:
```
$ ./kal -e -120 -s GSM900
$ ./kal -e -60 -s GSM900
$ ./kal -e -0 -s GSM900
$ ./kal -e 60 -s GSM900
$ ./kal -e 120 -s GSM900
```
look for the best results, with frequency offset nearest to 0.
taking the best range .. you might want to iterate or start `kal -c ` for the most powerful channel.
don't forget to warm up the dongle!, e.g. repeat until reported offsets get stable.

huhhh, this took a while!

@ValZapod : what are your results now?

**Comment by hayguen** [comment]
to amend my previous observations, now found following text in the summary of https://github.com/steve-m/kalibrate-rtl/blob/master/README.md:

> This project can work only correct the a small offset of ppm. You need to either get a rough initial estimate yourself, or use a project which can correct larger offsets automatically.



being precise, 'small offset' is 40 kHz at it's max; see https://github.com/steve-m/kalibrate-rtl/blob/master/src/offset.cc#L38

**Comment by ValZapod** [comment]
Nothing of what you proposed really makes any difference. Well, you have lots of other channels compared to me with much higher precision.(( I now think it is just my little antenna issue.

> oversampling of factor 2 or even more is used: samplerate >= symbolrate * 2.

About that. On master "PPL not locked!" is actually different underlying frequency than on those bisected commits. May that be smth bad?

**Comment by hayguen** [comment]
> On master "PPL not locked!" is actually different underlying frequency than on those bisected commits. May that be smth bad?

Sorry, I don't understand what you mean

Can you post the output of Kal with -e 55, with latest librtlsdr?, if your initial output was with -e 29.

**Comment by ValZapod** [comment]
> Kal with -e 55,
```
Found 1 device(s):
  0:  Astrometa DVB-T/DVB-T2

Using device 0: Astrometa DVB-T/DVB-T2
LOG: rtlsdr_open(0)
Found Rafael Micro R828D tuner
LOG: rtlsdr_get_xtal_freq(rtl_freq, tuner_freq)
LOG: rtlsdr_get_xtal_freq(rtl_freq, tuner_freq)
LOG: rtlsdr_set_sample_rate(samp_rate 270833)
Exact sample rate is: 270833.002142 Hz
LOG: rtlsdr_get_xtal_freq(rtl_freq, tuner_freq)
LOG: rtlsdr_set_freq_correction(ppm 55)
LOG: rtlsdr_get_xtal_freq(rtl_freq, tuner_freq)
LOG: rtlsdr_get_xtal_freq(rtl_freq, tuner_freq)
kal: Scanning for GSM-900 base stations.
GSM-900:
    chan:   25 (940.0MHz + 26.366kHz)    power:  178010.41
    chan:   26 (940.2MHz + 15.623kHz)    power:  549259.32
    chan:   49 (944.8MHz + 16.930kHz)    power:  247524.20
    chan:   72 (949.4MHz + 27.830kHz)    power:  362712.61
...chan 124
Difference of offsets between channels is >1kHz. This likely means that the correct PPM is too far away and you need to provide a rough estimate using the '-e' option. Try tuning against a local FM radio or other known frequency first.

```



> initial output was with -e 29.

There were no output with 29. But here you are:

```
Found 1 device(s):
  0:  Astrometa DVB-T/DVB-T2

Using device 0: Astrometa DVB-T/DVB-T2
LOG: rtlsdr_open(0)
Found Rafael Micro R828D tuner
LOG: rtlsdr_get_xtal_freq(rtl_freq, tuner_freq)
LOG: rtlsdr_get_xtal_freq(rtl_freq, tuner_freq)
LOG: rtlsdr_set_sample_rate(samp_rate 270833)
Exact sample rate is: 270833.002142 Hz
LOG: rtlsdr_get_xtal_freq(rtl_freq, tuner_freq)
LOG: rtlsdr_set_freq_correction(ppm 29)
LOG: rtlsdr_get_xtal_freq(rtl_freq, tuner_freq)
LOG: rtlsdr_get_xtal_freq(rtl_freq, tuner_freq)
kal: Scanning for GSM-900 base stations.
GSM-900:
    chan:   25 (940.0MHz + 2.632kHz)    power:  203766.83
    chan:   26 (940.2MHz + 2.482kHz)    power:  431308.04
    chan:   49 (944.8MHz + 3.162kHz)    power:  317539.70
    chan:   72 (949.4MHz - 6.426kHz)    power:  651166.84
    chan:   73 (949.6MHz + 3.591kHz)    power:  313990.13
...chan 124
Difference of offsets between channels is >1kHz. This likely means that the correct PPM is too far away and you need to provide a rough estimate using the '-e' option. Try tuning against a local FM radio or other known frequency first.
```
